{% set name = "nbclassic" %}
{% set version = "0.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c3ee67b2c94d6b88b4566e485040f32c46bf17894850ce4a0355fc420e8470d

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -c "__import__('shutil').rmtree('tests')"
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-nbclassic = nbclassic.notebookapp:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyter_server >=1.0.1,<2.0.0
    - notebook <7

test:
  imports:
    - nbclassic

about:
  home: http://github.com/jupyterlab/nbclassic
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Notebook as a Jupyter Server Extension.
  dev_url: https://github.com/jupyterlab/nbclassic
  description: |
    This project prepares for a future where JupyterLab and other frontends
    switch to Jupyter Server for their Python Web application backend. Using
    this package, users can launch Jupyter Notebook, JupyterLab and other
    frontends side-by-side on top of the new Python server backend.

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
